ren горбуша.png  "pink salmon.png"
ren гребешок.png "scallop.png"
ren кальмар.png  "squid.png"
ren камбала.png  "flounder.png"
ren кета.png "chum.png"
ren кижуч.png  "coho.png"
ren корюшка.png  "smelt.png"
ren креветка_углохвостая.png "shrimp.png"
ren лангустины.png "langoustines.png"
ren мидии.png  "mussels.png"
ren мидии_2.jpg  "mussels_2.png"
ren мидии_2.png  "mussels_2.png"
ren минтай.png "pollock.png"
ren сельдь.png "herring.png"
ren семга.png  "salmon.png"
ren скумбрия.png "mackerel.png"
ren тигровая_креветка.png  "Tiger shrimp.png"
ren треска.png "cod.png"
ren форель.png "trout.png"
